#!/usr/bin/env python3

import sys
import sympy

def factorize(number):
    factors = sympy.factorint(number)
    return factors

def main():
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    filename = sys.argv[1]

    with open(filename, 'r') as file:
        numbers = [int(line.strip()) for line in file]

    for number in numbers:
        factors_dict = factorize(number)
        factors_str = "*".join([f"{factor}^{exponent}" if exponent > 1 else str(factor) for factor, exponent in factors_dict.items()])
        print(f"{number}={factors_str}")

if __name__ == "__main__":
    main()
